#!/usr/bin/env python3

from __future__ import annotations

import argparse
import html
import os
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib


LABWC_BEGIN_MARKER = "<!-- uconsole-mapper:keybinds begin -->"
LABWC_END_MARKER = "<!-- uconsole-mapper:keybinds end -->"
SESSION_LAUNCHER = "/usr/local/bin/uconsole-launch-in-session"


@dataclass(slots=True)
class RightShiftBinding:
    key: str
    command: str


@dataclass(slots=True)
class LabwcBinding:
    key: str
    command: str
    comment: str | None = None


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("~/.config/uconsole-mapper/desktop-keybinds.toml").expanduser(),
    )
    parser.add_argument(
        "--keyd-out",
        type=Path,
        default=script_dir / "keyd-uconsole-mapper",
    )
    parser.add_argument(
        "--labwc-out",
        type=Path,
        default=script_dir / "labwc-keybinds.xml",
    )
    return parser.parse_args()


def load_config(path: Path) -> tuple[list[RightShiftBinding], list[LabwcBinding]]:
    raw = tomllib.loads(path.read_text(encoding="utf-8"))
    rightshift = raw.get("rightshift", {})
    labwc = raw.get("labwc", {})

    rightshift_raw = rightshift.get("bindings", [])
    labwc_raw = labwc.get("bindings", [])

    rightshift_keys: set[str] = set()
    rightshift_bindings: list[RightShiftBinding] = []
    for index, item in enumerate(rightshift_raw):
        if not isinstance(item, dict):
            raise ValueError(f"rightshift.bindings[{index}] must be a table")
        key = str(item.get("key", "")).strip().lower()
        command = str(item.get("command", "")).strip()
        if not key or not command:
            raise ValueError(f"rightshift.bindings[{index}] requires key and command")
        if key in rightshift_keys:
            raise ValueError(f"duplicate RightShift binding for key {key}")
        rightshift_keys.add(key)
        rightshift_bindings.append(RightShiftBinding(key=key, command=command))

    labwc_keys: set[str] = set()
    labwc_bindings: list[LabwcBinding] = []
    for index, item in enumerate(labwc_raw):
        if not isinstance(item, dict):
            raise ValueError(f"labwc.bindings[{index}] must be a table")
        key = str(item.get("key", "")).strip()
        command = str(item.get("command", "")).strip()
        if not key or not command:
            raise ValueError(f"labwc.bindings[{index}] requires key and command")
        if key in labwc_keys:
            raise ValueError(f"duplicate labwc binding for key {key}")
        labwc_keys.add(key)
        labwc_bindings.append(LabwcBinding(key=key, command=command))

    return rightshift_bindings, labwc_bindings


def render_keyd(bindings: list[RightShiftBinding]) -> str:
    lines = [
        "# Auto-generated by generate_desktop_keybinds.py",
        "# RightShift stays a normal Shift modifier for unmapped combos.",
        "# Listed RightShift combos launch commands directly from keyd.",
    ]
    if not bindings:
        lines.append("# No RightShift desktop bindings configured.")
        return "\n".join(lines) + "\n"

    lines.extend(
        [
            "[main]",
            "rightshift = layer(uconsole_rightshift)",
            "",
            "[uconsole_rightshift:S]",
        ]
    )
    for binding in bindings:
        launched = shlex.quote(expand_command_home(binding.command))
        lines.append(f"# RightShift+{binding.key.upper()} -> {binding.command}")
        lines.append(f"{binding.key} = command({SESSION_LAUNCHER} {launched})")
    return "\n".join(lines) + "\n"


def render_labwc(bindings: list[LabwcBinding]) -> str:
    lines = [LABWC_BEGIN_MARKER]
    for binding in bindings:
        if binding.comment:
            lines.append(f"<!-- {binding.comment} -->")
        command = html.escape(expand_command_home(binding.command), quote=True)
        lines.append(f'<keybind key="{binding.key}">')
        lines.append(f'  <action name="Execute" command="{command}" />')
        lines.append("</keybind>")
    lines.append(LABWC_END_MARKER)
    return "\n".join(lines) + "\n"


def expand_command_home(command: str) -> str:
    try:
        parts = shlex.split(command, posix=True)
    except ValueError:
        return command

    if not parts:
        return command

    if parts[0].startswith("~/"):
        parts[0] = os.path.expanduser(parts[0])
        return shlex.join(parts)

    return command


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    config_path = args.config.expanduser()
    if not config_path.exists():
        print(f"config not found: {config_path}", file=sys.stderr)
        return 1

    rightshift_bindings, labwc_bindings = load_config(config_path)
    write_text(args.keyd_out, render_keyd(rightshift_bindings))
    write_text(args.labwc_out, render_labwc(labwc_bindings))

    print(
        f"generated {args.keyd_out} and {args.labwc_out} from {config_path} "
        f"({len(rightshift_bindings)} RightShift bindings, {len(labwc_bindings)} labwc bindings)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
