#!/usr/bin/env python3

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import subprocess
import sys
import time
import re


DEFAULT_DEVICE_NAMES = ["ClockworkPI uConsole Keyboard"]
DEFAULT_MONITOR_CMD = ["keyd.rvaiya", "monitor"]
DEFAULT_CONFIG_PATH = Path("/etc/keyd/default.conf")
MANAGED_COMMENT = "# Auto-generated by sync_keyd_default_conf.py"
INCLUDE_LINE = "include uconsole-mapper"
DEVICE_RE = re.compile(r"^device added:\s+(\S+)\s+(.+?)\s+\(/dev/input/event\d+\)$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
    )
    parser.add_argument(
        "--device-name",
        action="append",
        default=[],
        help="Input device name to match from `keyd.rvaiya monitor` output. May be supplied multiple times.",
    )
    parser.add_argument(
        "--timeout-ms",
        type=int,
        default=2500,
    )
    return parser.parse_args()


def backup_path(path: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return path.with_name(f"{path.name}.bak.{stamp}")


def detect_device_ids(device_names: list[str], timeout_ms: int) -> list[str]:
    proc = subprocess.Popen(
        DEFAULT_MONITOR_CMD,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    try:
        found: dict[str, str] = {}
        deadline = time.monotonic() + timeout_ms / 1000
        while time.monotonic() < deadline:
            line = proc.stdout.readline() if proc.stdout is not None else ""
            if not line:
                if proc.poll() is not None:
                    break
                time.sleep(0.05)
                continue

            match = DEVICE_RE.match(line.strip())
            if not match:
                continue

            device_id, name = match.groups()
            if name in device_names and name not in found:
                found[name] = device_id
                if len(found) == len(device_names):
                    break

        missing = [name for name in device_names if name not in found]
        if missing:
            raise RuntimeError(f"unable to detect keyd device ids for: {', '.join(missing)}")
        return [found[name] for name in device_names]
    finally:
        proc.kill()
        proc.wait(timeout=1)


def render_config(device_ids: list[str]) -> str:
    lines = [
        MANAGED_COMMENT,
        "[ids]",
    ]
    lines.extend(device_ids)
    lines.extend(
        [
            "",
            INCLUDE_LINE,
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    config_path = args.config
    config_path.parent.mkdir(parents=True, exist_ok=True)

    device_names = args.device_name or DEFAULT_DEVICE_NAMES
    device_ids = detect_device_ids(device_names, args.timeout_ms)
    updated = render_config(device_ids)

    if config_path.exists():
        original = config_path.read_text(encoding="utf-8")
        if original == updated:
            print(f"unchanged {config_path}")
            return 0

        backup = backup_path(config_path)
        backup.write_text(original, encoding="utf-8")
        config_path.write_text(updated, encoding="utf-8")
        print(f"updated {config_path}")
        print(f"backup {backup}")
        return 0

    config_path.write_text(updated, encoding="utf-8")
    print(f"created {config_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
